package generate_test

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/modernice/opendocs/generate"
	"github.com/modernice/opendocs/internal"
	igen "github.com/modernice/opendocs/internal/generate"
	"github.com/modernice/opendocs/internal/tests"
)

func mockService(repo fs.FS) (*igen.Service, []generate.Generation) {
	svc := igen.MockService().
		WithDoc("operations.go", "Add", "Add adds numbers together.").
		WithDoc("operations.go", "Sub", "Sub subtracts numbers.").
		WithDoc("operations.go", "Mul", "Mul multiplies numbers.").
		WithDoc("operations.go", "Div", "Div divides numbers.")
	return svc, []generate.Generation{
		{
			Path:       "operations.go",
			Identifier: "Add",
			Doc:        "Add adds numbers together.",
		},
		{
			Path:       "operations.go",
			Identifier: "Sub",
			Doc:        "Sub subtracts numbers.",
		},
		{
			Path:       "operations.go",
			Identifier: "Mul",
			Doc:        "Mul multiplies numbers.",
		},
		{
			Path:       "operations.go",
			Identifier: "Div",
			Doc:        "Div divides numbers.",
		},
	}
}

func TestGenerator_Generate(t *testing.T) {
	root := filepath.Join(tests.Must(os.Getwd()), "testdata", "gen", "calculator")
	tests.WithRepo("calculator", root, func(repoFS fs.FS) {
		svc, want := mockService(repoFS)
		g := generate.New(svc)

		gens, errs, err := g.Generate(context.Background(), repoFS)
		if err != nil {
			t.Fatalf("Generate() should not return an error; got %q", err)
		}

		result := drain(t, gens, errs)

		tests.ExpectGenerations(t, want, result)
	})
}

func TestFooter(t *testing.T) {
	root := filepath.Join(tests.Must(os.Getwd()), "testdata", "gen", "footer")
	tests.WithRepo("calculator", root, func(repoFS fs.FS) {
		svc, want := mockService(repoFS)

		for i, gen := range want {
			gen.Doc = fmt.Sprintf("%s\n\nGenerated by opendocs.", gen.Doc)
			want[i] = gen
		}

		g := generate.New(svc)

		gens, errs, err := g.Generate(context.Background(), repoFS, generate.Footer("Generated by opendocs."))
		if err != nil {
			t.Fatalf("Generate() should not return an error; got %q", err)
		}

		result := drain(t, gens, errs)

		tests.ExpectGenerations(t, want, result)
	})
}

func drain[T any](t *testing.T, vals <-chan T, errs <-chan error) []T {
	out, err := internal.Drain(vals, errs)
	if err != nil {
		t.Fatalf("drain generations: %v", err)
	}
	return out
}
