package git

import "strings"

func CommitDescription(identifiers map[string][]string) string {
	var sb strings.Builder

	for file, idents := range identifiers {
		sb.WriteString(file + ":")
		for _, identifier := range idents {
			sb.WriteString("\t - " + identifier)
		}
	}

	sb.WriteString("\n\nGenerated by github.com/modernice/opendocs")

	return sb.String()
}
